<<<<<<<< HEAD:CUBESEED/app/(processor)/dashboard/layout.tsx
import Navbar from "@/component/navbar/navbar";
import DashboardNavbar from "@/component/dashboard/dashboard-navbar/dashboard-navbar";
========
import Navbar from "@/component/navbar/Navbar";
import DashboardNavbar from "@/component/dashboard/DashboardNavbar/DashboardNavbar";
import DashboardSidePannel from "@/component/dashboard/DashboardSidePannel";
>>>>>>>> a44626a34215f108300fa23e1a6a0e5e4f07b8a2:CUBESEED/app/(farmer)/dashboard/layout.tsx

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky inset-0 ">
        <Navbar />
      </header>
      <div>
        <aside className="w-[250px] h-screen fixed inset-0 bg-white shadow-2xl">
          <DashboardSidePannel/>
        </aside>
        <main className="ml-[250px]">{children}</main>
      </div>
    </div>
  );
}
